version: "3.8"
services:
  front:
    build:
      context: ./
      dockerfile: ./docker/front/Dockerfile
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - "./front:/front"
    working_dir: /front

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    # command: "go run main.go"
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - "./api:/go/src"
    working_dir: /go/src
