version: "3.8"
services:
  front:
    build:
      context: ./
      dockerfile: ./docker/front/Dockerfile
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - "./front:/front"
    working_dir: /front
